# Generated by Django 5.2.10 on 2026-03-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='messageBot',
            fields=[
                ('messageID', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('messageContents', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='patrollerUser',
            fields=[
                ('userID', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('gameCurrency', models.JSONField()),
                ('messageList', models.JSONField()),
            ],
        ),
    ]
