# Generated by Django 5.2.10 on 2026-03-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakerapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolleruser',
            name='rivalList',
            field=models.JSONField(default='blah'),
            preserve_default=False,
        ),
    ]
