# Generated by Django 5.2.10 on 2026-04-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakerapi', '0002_patrolleruser_rivallist'),
    ]

    operations = [
        migrations.AddField(
            model_name='patrolleruser',
            name='userCharacters',
            field=models.JSONField(default='blah'),
            preserve_default=False,
        ),
    ]
