"""
Django settings for breadbreaker project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^v6n$bw2#ir!)2r4&pee_to-_eh4nal0icefcvlbjc5$kdcc5w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['breadbreakerzz.local', 'dbtb-prd.breadbreakerzz.local', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'channels',
    #'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'breakerapi',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
}

MIDDLEWARE = [
    #'corsheaders.middleware.CorsMiddleware',
    'ipinfo_django.middleware.IPinfoAsyncMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', #for static file serving
    #'django.contrib.sessions.middleware.SessionMiddleware', #remove vary header, also sessions only work on browsers
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    #'django.contrib.auth.middleware.AuthenticationMiddleware', #remove with session middleware
    #'django.contrib.messages.middleware.MessageMiddleware', #remove with session middleware
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'request_logging.middleware.LoggingMiddleware', #TODO: clean up the digusting console
    'breadbreaker.middleware.HeaderOrderMiddleWare',
    'ipinfo_django.middleware.IPinfoMiddleware',
]

ROOT_URLCONF = 'breadbreaker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'breadbreaker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}


STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'loggers': {
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        "": {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}


ASGI_APPLICATION = 'breadbreaker.asgi.application'

REDIS_URL = 'redis://breadbreakerzz.local:6379' 

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}

SECURE_CONTENT_TYPE_NOSNIFF = False #removes no sniff header

SECURE_REFERRER_POLICY = None #remove referrer header

SECURE_CROSS_ORIGIN_OPENER_POLICY = None


#X_FRAME_OPTIONS = 'SAMEORIGIN'

#CORS_URLS_REGEX = r'^/(LALALALALA/000000/|LALALALALA/025348/)/.*$'

#CORS_ALLOW_ALL_ORIGINS  = True

#CORS_ALLOW_CREDENTIALS = False  # Disable credentials for public APIs


#when public
#CORS_ALLOWED_ORIGINS = [
    #"https://yourdomain.com",
#]

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
        'LOCATION': './cache',
    }
}

ENV_HOST = os.environ['ENV_HOST']
PRD_HOST = os.environ['PRD_HOST']
UDP_HOST = os.environ['UDP_HOST']
UDP_PORT = os.environ['UDP_PORT']
